### ISSUE TITLE
Template `vars` have type `map[interface {}]interface {}` instead of `map[string]interface {}`

### ISSUE THREAD

**Issue by 10hendersonm** [go-vela/compiler#164]
https://github.com/go-vela/compiler/blob/ef890ebd54b82cfff886631e5818ce9ea4c20ebe/template/native/render.go#L16-L47

> ⚠️ I'm a JavaScript dev with pretty low knowledge of GoLang. Anything and everything I say is probably wrong.

I'm unsure if this is occurring at the root level, or only in deeper properties, but I'm unable to call the spring function `toJson` (or `mustToJson`) to wholesale take an object from `vars` and render it out into my template.

Given a `.vela.yml` like...
> ℹ️ It doesn't have to be this absurdly deep, this was a test I wrote while trying to fix.
```yml
steps:
  - name: praxis-pipeline
    template:
      name: praxis
      vars:
        build_environments:
          - name: foo
            ruleset:
              some:
                deep:
                  property:
                    tree:
                      - foo
                      - bar
                      - baz
```

And content within a template such as...
```
{{- range $buildEnv := .build_environments -}}
  {{- $reactAppEnv := $buildEnv.name -}}
  {{- $buildRuleset := $buildEnv.ruleset }}
  # Build the app for the {{ $reactAppEnv }} environment
  - name: {{ $reactAppEnv }}_build
    <<: *node-image
    environment:
      REACT_APP_ENV: {{ $reactAppEnv }}
    commands:
      - npm run build
  {{- if $buildRuleset }}
    ruleset: {{ mustToJson $buildRuleset }}
  {{- end }}
{{- end }}
```

It breaks with an error like...
```
unable to execute template: template: praxis-pipeline:84:16: executing "praxis-pipeline" at <mustToJson $buildRuleset>: error calling mustToJson: json: unsupported type: map[interface {}]interface {}
```

This may have to do with the default typings of `go-yaml` - `defaultMapType = reflect.TypeOf(map[interface{}]interface{}{})` (see https://github.com/go-yaml/yaml/issues/139).
